❯ cargo r    Compiling polygon v0.1.0 (/home/gy/my_projects/Cpp_Lang/12121212/rust_gui_vulkan_trainning/003_examples/polygon)     Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.20s      Running `target/debug/polygon` Using device: NVIDIA GeForce RTX 3060 Ti (type: DiscreteGpu)
thread 'main' (152850) panicked at src/main.rs:499:14:
called `Result::unwrap()` on an `Err` value: a validation error occurred

Caused by:
    create_info.stages[1].entry_point: the requirements for descriptor set 0 binding 0 were not met: no such binding exists in the pipeline layout

Vulkan VUIDs:
    VUID-VkGraphicsPipelineCreateInfo-layout-00756
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace